"""initial

Revision ID: 622fd6a7df49
Revises:
Create Date: 2020-04-16 07:34:13.219075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "622fd6a7df49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fluid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "component",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("fluid_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["fluid_id"], ["fluid.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("component")
    op.drop_table("fluid")
    # ### end Alembic commands ###
