repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7
        files: ^main-api/.*\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: '3.7.9'
    hooks:
      -   id: flake8
          files: ^main-api/.*\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
      - id: bandit
        args: [-l, --recursive, -x, tests]
        files: ^main-api/.*\.py$
  - repo: https://github.com/timothycrosley/isort
    rev: '4.3.21-2'
    hooks:
      -   id: isort
          files: ^main-api/.*\.py$
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
        files: ^web/.*\.(ts|tsx|js|css|html|json)$
        args: ['--config=web/.prettierrc.js']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
      -   id: mypy
          files: ^main-api/.*\.py$
          additional_dependencies:
            - 'sqlalchemy-stubs'
